version: "3.8"
services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./sakila:/docker-entrypoint-initdb.d
      - ./sakila:/workspaces/sakila
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  mariadb_data:
