version: "3.8"
services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auditoria
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./sakila:/docker-entrypoint-initdb.d
      - ./sakila:/workspaces/sakila
      - mariadb_data:/var/lib/mysql
    restart: always

  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8080:80"
    environment:
      -  DB_SERVER=dvwa-db
      - DB_DATABASE=dvwa_db
      - DB_USER=admin
      - DB_PASSWORD=password
    volumes:
      - ./config.inc.php:/var/www/html/config/config.inc.php
    depends_on:
      - mariadb
    restart: always

  dvwa-db:
    image: mariadb:10.11
    container_name: dvwa-db
    environment:
      MYSQL_ROOT_PASSWORD: dvwaroot
      MYSQL_DATABASE: dvwa_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - dvwa_data:/var/lib/mysql
    restart: always


volumes:
  mariadb_data:
  dvwa_data:
